name: build-test

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: build
        run: GO11MODULE=on CGO_ENABLED=0 go build -a -ldflags '-w -s' .
